apiVersion: apps/v1
kind: Deployment
metadata:
  name: prices-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prices
  template:
    metadata:
      labels:
        app: prices
    spec:
      containers:
        - image: as9721/prices:2023-01-10-02-13-34
          name: prices
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://primerjalnik-cen-server.mysql.database.azure.com:3306/primerjalnik-cen?useSSL=true
            - name: spring.datasource.username
              value: adminRso
            - name: spring.datasource.password
              value: Rso2022@
            - name: LOGBACK_DESTINATION
              value: b37028e3-1115-4b76-af74-20c97b9c0391-ls.logit.io:25428
            - name: CONFIG_SERVER_URL
              value: http://20.4.194.189:8888
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: prices
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: prices
